# mkdocs.yml
---
site_name: "Diagrammer.Core"
site_url: "https://diagrammer.techmyth.blog"
repo_url: "https://github.com/rebelinux/Diagrammer.Core"
repo_name: "rebelinux/Diagrammer.Core"

site_author: "Jonathan Colon"
copyright: "(c) 2025 Jonathan Colon."

docs_dir: "Docs"

# Customizations
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rebelinux
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jcolonfzenpr
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/jcolonfpr.bsky.social

# Plugins
plugins:
  - glightbox
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      fallback_to_build_date: true
  - social:
      cards_layout_options:
        font_family: Montserrat Alternates
        color: "#063561"

markdown_extensions:
  - pymdownx.snippets:
      url_download: true
  - mkdocs_graphviz
  - attr_list
  - admonition
  - meta
  - tables
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      use_pygments: true
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/favicon.ico
  highlightjs: true
  hljs_languages:
    - yaml
    - powershell
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  language: en
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.sections
    - navigation.footer
    - navigation.top
    - toc.follow
    - toc.integrate

# Page Navigation
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: start/introduction.md
      - Installation: start/installation.md
  - Developer Guide:
      - Commands: dev-guide/commands.md
      - Examples:
          - Example 1: dev-guide/examples/example1.md
          - Example 2: dev-guide/examples/example2.md
          - Example 3: dev-guide/examples/example3.md
          - Example 4: dev-guide/examples/example4.md
          - Example 5: dev-guide/examples/example5.md
          - Example 6: dev-guide/examples/example6.md
          - Example 7: dev-guide/examples/example7.md
          - Example 8: dev-guide/examples/example8.md
          - Example 9: dev-guide/examples/example9.md
          - Example 10: dev-guide/examples/example10.md
          - Example 11: dev-guide/examples/example11.md
          - Example 12: dev-guide/examples/example12.md
          - Example 13: dev-guide/examples/example13.md
          - Example 14: dev-guide/examples/example14.md
          - Example 15: dev-guide/examples/example15.md
      - Advanced Examples:
          - Advanced Example 1: dev-guide/examples/advancedexample1.md
          - Advanced Example 2: dev-guide/examples/advancedexample2.md
  - Support: support.md
  - About:
      - Contact: about/contact.md
      - Changelog: about/changelog.md
      - License: about/license.md
